"use client";
import { useEffect,useMemo,useState } from "react";
type Row={id:number;reference:string;name:string;employeeId:string;phone:string;email?:string;department?:string;modelName:string;price:number;years:number;monthly:number;status:string;createdAt:string;updatedAt:string};
const statuses=[['received','Demande reçue'],['review','En vérification'],['approved','Financement approuvé'],['construction','Construction en cours'],['delivered','Maison livrée'],['rejected','À compléter']];
const money=(n:number)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
export default function AdminDashboard({user,signout}:{user:string;signout:string}){
 const [rows,setRows]=useState<Row[]>([]),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[loading,setLoading]=useState(true),[active,setActive]=useState<Row|null>(null);
 async function load(){setLoading(true);const r=await fetch('/api/admin/reservations');if(r.ok)setRows((await r.json()).reservations);setLoading(false)}
 useEffect(()=>{fetch('/api/admin/reservations').then(r=>r.ok?r.json():{reservations:[]}).then(data=>{setRows(data.reservations);setLoading(false)})},[]);
 const filtered=useMemo(()=>rows.filter(r=>(status==='all'||r.status===status)&&(`${r.reference} ${r.name} ${r.employeeId} ${r.phone}`.toLowerCase().includes(query.toLowerCase()))),[rows,query,status]);
 async function update(id:number,next:string){await fetch('/api/admin/reservations',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,status:next})});await load();setActive(a=>a?{...a,status:next}:a)}
 return <main className="admin"><header><div><p className="eyebrow dark">KWAKO NYUMBANI</p><h1>Tableau de gestion</h1></div><div className="adminUser"><span>{user}</span><a href={signout}>Déconnexion</a></div></header><section className="adminStats"><article><span>Dossiers reçus</span><b>{rows.length}</b></article><article><span>À vérifier</span><b>{rows.filter(r=>['received','review'].includes(r.status)).length}</b></article><article><span>Approuvés</span><b>{rows.filter(r=>['approved','construction','delivered'].includes(r.status)).length}</b></article><article><span>Valeur des demandes</span><b>{money(rows.reduce((s,r)=>s+r.price,0))}</b></article></section><section className="adminPanel"><div className="adminTools"><input aria-label="Rechercher" placeholder="Rechercher nom, référence, matricule…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Tous les statuts</option>{statuses.map(s=><option key={s[0]} value={s[0]}>{s[1]}</option>)}</select><button onClick={load}>Actualiser</button></div>{loading?<p className="empty">Chargement des dossiers…</p>:filtered.length===0?<p className="empty">Aucun dossier trouvé.</p>:<div className="tableWrap"><table><thead><tr><th>Référence</th><th>Acquéreur</th><th>Maison</th><th>Mensualité</th><th>Statut</th><th></th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><b>{r.reference}</b><small>{new Date(r.createdAt).toLocaleDateString('fr-FR')}</small></td><td>{r.name}<small>{r.employeeId} • {r.phone}</small></td><td>{r.modelName}<small>{money(r.price)} • {r.years} ans</small></td><td>{money(r.monthly)}</td><td><span className={`status ${r.status}`}>{statuses.find(s=>s[0]===r.status)?.[1]}</span></td><td><button className="open" onClick={()=>setActive(r)}>Ouvrir</button></td></tr>)}</tbody></table></div>}</section>{active&&<div className="modalBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setActive(null)}}><div className="modal adminDetail"><button className="close" onClick={()=>setActive(null)}>×</button><p className="eyebrow dark">{active.reference}</p><h2>{active.name}</h2><dl><div><dt>Matricule</dt><dd>{active.employeeId}</dd></div><div><dt>Téléphone</dt><dd>{active.phone}</dd></div><div><dt>E-mail</dt><dd>{active.email||'—'}</dd></div><div><dt>Département</dt><dd>{active.department||'—'}</dd></div><div><dt>Maison</dt><dd>{active.modelName} • {money(active.price)}</dd></div><div><dt>Financement</dt><dd>{active.years} ans • {money(active.monthly)}/mois</dd></div></dl><label>Mettre à jour le statut<select value={active.status} onChange={e=>update(active.id,e.target.value)}>{statuses.map(s=><option key={s[0]} value={s[0]}>{s[1]}</option>)}</select></label></div></div>}</main>
}
